# Generated by Django 5.1 on 2024-11-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinebanking',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='onlinebanking',
            name='adminOnlineBank',
        ),
        migrations.RemoveField(
            model_name='onlinebanking',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='onlinebanking',
            name='bankname',
            field=models.CharField(default='ee', max_length=250),
        ),
        migrations.AddField(
            model_name='onlinebanking',
            name='username',
            field=models.CharField(default='user', max_length=300),
        ),
        migrations.DeleteModel(
            name='DriversLicense',
        ),
    ]
