# Generated by Django 5.1 on 2024-11-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0002_remove_onlinebanking_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinebanking',
            name='bankname',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='onlinebanking',
            name='username',
            field=models.CharField(max_length=300),
        ),
    ]
