# Generated by Django 5.1 on 2024-09-02 12:24

import django.contrib.auth.password_validation
import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(validators=[django.contrib.auth.password_validation.validate_password]),
        ),
    ]
