# Generated by Django 5.1 on 2024-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0003_alter_mail_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverslicense',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
