# Generated by Django 5.1 on 2024-11-24 23:27

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0003_alter_onlinebanking_bankname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinebanking',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
