# Generated by Django 5.1 on 2024-12-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0006_alter_certificates_options_certificates_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
