# Generated by Django 5.1 on 2024-12-07 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0007_alter_certificates_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcard',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='mail',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='onlinebanking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
