# Generated by Django 5.1 on 2024-12-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0008_alter_creditcard_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
