# Generated by Django 5.1 on 2024-10-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0008_alter_customuser_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='pin',
        ),
        migrations.AddField(
            model_name='pin',
            name='pin_hash',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
