# Generated by Django 5.1 on 2024-12-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0009_socialmedia_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'Tiktok'), ('telegram', 'Telegram'), ('linkdin', 'Linkdin'), ('x', 'X'), ('youtube', 'youtube'), ('behance', 'Behance'), ('snapchap', 'Snapchat')], max_length=20, null=True),
        ),
    ]
