# Generated by Django 5.1 on 2024-10-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0009_remove_pin_pin_pin_pin_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='pin_hash',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
