# Generated by Django 5.1 on 2024-12-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0010_alter_socialmedia_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='platform',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('yahoo', 'Yahoo'), ('apple email', 'Apple Email'), ('aol mail', 'Aol Mail'), ('outlook', 'Outlook'), ('zohoo', 'Zohoo'), ('proton mail', 'Proton Mail'), ('gmx', 'Gmx')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'Tiktok'), ('telegram', 'Telegram'), ('linkdin', 'Linkdin'), ('x', 'X'), ('youtube', 'youtube'), ('behance', 'Behance'), ('snapchat', 'Snapchat')], max_length=20, null=True),
        ),
    ]
