# Generated by Django 5.1 on 2024-10-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0010_alter_pin_pin_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, default='0000', max_length=4),
        ),
    ]
