# Generated by Django 5.1 on 2024-12-10 22:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0011_mail_platform_alter_socialmedia_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='document_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='certificate_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='platform',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('yahoo', 'Yahoo'), ('appleemail', 'AppleEmail'), ('aolmail', 'AolMail'), ('outlook', 'Outlook'), ('zohoo', 'Zohoo'), ('protonmail', 'ProtonMail'), ('gmx', 'Gmx')], max_length=20, null=True),
        ),
    ]
