# Generated by Django 5.1 on 2024-12-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0012_remove_document_file_document_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.URLField(blank=True, null=True, verbose_name='file'),
        ),
    ]
