# Generated by Django 5.1 on 2024-12-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0013_alter_document_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='certificate_document',
            field=models.URLField(blank=True, null=True, verbose_name='file'),
        ),
    ]
