# Generated by Django 5.1 on 2024-10-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0014_alter_socialmedia_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
