# Generated by Django 5.1 on 2024-11-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0015_alter_socialmedia_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='adminMail',
        ),
        migrations.AlterField(
            model_name='mail',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='AdminMail',
        ),
    ]
