# Generated by Django 5.1 on 2024-11-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0017_remove_creditcard_bank_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificates',
            old_name='document',
            new_name='certificate_document',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='certificateID',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='certificate_url',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='issuing_Organization',
        ),
    ]
