# Generated by Django 5.1 on 2024-11-07 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0018_rename_document_certificates_certificate_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='color',
            field=models.CharField(default='#FF1100', help_text='Card color in hex format (e.g., #FF1100 for red).', max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6})$', 'Color must be a valid hex code.')]),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
