# Generated by Django 5.1 on 2024-11-10 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0019_creditcard_color_alter_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='certificate_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'PIN must be a 16-digit number.')]),
        ),
    ]
