# Generated by Django 5.1 on 2024-11-12 08:06

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecuraApp', '0020_alter_certificates_certificate_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
